(()=>{const data={
tr:{kicker:"BİZİ KEŞFET",title:"Salon White'ın<br><em>hikâyesine yakından bakın.</em>",link:"Hakkımızda",experience:{title:"Deneyim ve tecrübe",copy:"15 yıllık deneyim, özenli uygulama ve kişisel stile odaklanan salon yaklaşımı."},team:{title:"Profesyonel ve samimi ekip",copy:"Güler yüzlü iletişim, ekip çalışması ve yerli-yabancı misafirler için rahat bir deneyim."},location:{title:"Merkezi ve turistik konum",copy:"SIRKECI & EMINÖNÜ ve Eminönü'nün merkezinde; tarihi duraklara, otellere ve toplu taşımaya yakın."}},
en:{kicker:"DISCOVER US",title:"Take a closer look at<br><em>the Salon White story.</em>",link:"About us",experience:{title:"Experience & expertise",copy:"15 years of experience, careful application and a focus on each guest's personal style."},team:{title:"Professional & welcoming team",copy:"Friendly communication, teamwork and a comfortable experience for local and international guests."},location:{title:"Central & tourist-friendly location",copy:"In the heart of SIRKECI & EMINÖNÜ, close to historic sights, hotels and public transport."}},
de:{kicker:"ENTDECKEN SIE UNS",title:"Entdecken Sie die<br><em>Salon-White-Geschichte.</em>",link:"Über uns",experience:{title:"Erfahrung & Fachkompetenz",copy:"15 Jahre Erfahrung, sorgfältige Arbeit und ein Fokus auf den persönlichen Stil."},team:{title:"Professionelles & herzliches Team",copy:"Freundliche Kommunikation, Teamarbeit und Komfort für lokale und internationale Gäste."},location:{title:"Zentrale & touristische Lage",copy:"Im Herzen von SIRKECI & EMINÖNÜ, nahe Sehenswürdigkeiten, Hotels und öffentlichen Verkehrsmitteln."}},
fr:{kicker:"DÉCOUVREZ-NOUS",title:"Découvrez de plus près<br><em>l'univers de Salon White.</em>",link:"À propos",experience:{title:"Expérience & savoir-faire",copy:"15 ans d'expérience, une application soignée et une attention portée au style personnel."},team:{title:"Équipe professionnelle & chaleureuse",copy:"Communication agréable, travail d'équipe et expérience confortable pour les visiteurs."},location:{title:"Emplacement central & touristique",copy:"Au cœur de SIRKECI & EMINÖNÜ, près des sites historiques, hôtels et transports publics."}},
es:{kicker:"DESCÚBRENOS",title:"Conoce de cerca<br><em>la historia de Salon White.</em>",link:"Sobre nosotros",experience:{title:"Experiencia y profesionalidad",copy:"15 años de experiencia, aplicación cuidadosa y atención al estilo personal."},team:{title:"Equipo profesional y cercano",copy:"Comunicación amable, trabajo en equipo y una experiencia cómoda para visitantes."},location:{title:"Ubicación céntrica y turística",copy:"En el corazón de SIRKECI & EMINÖNÜ, cerca de lugares históricos, hoteles y transporte público."}},
ru:{kicker:"УЗНАЙТЕ НАС",title:"Познакомьтесь ближе с<br><em>историей Salon White.</em>",link:"О нас",experience:{title:"Опыт и профессионализм",copy:"15 лет опыта, аккуратная работа и внимание к индивидуальному стилю."},team:{title:"Профессиональная и дружелюбная команда",copy:"Тёплое общение, командная работа и комфорт для местных и иностранных гостей."},location:{title:"Центральное и туристическое расположение",copy:"В самом центре Сиркеджи и Эминёню, рядом с достопримечательностями, отелями и транспортом."}},
ar:{kicker:"اكتشفنا",title:"تعرّف عن قرب على<br><em>قصة Salon White.</em>",link:"من نحن",experience:{title:"الخبرة والاحتراف",copy:"15 عاماً من الخبرة، تطبيق دقيق واهتمام بالأسلوب الشخصي لكل ضيف."},team:{title:"فريق محترف وودود",copy:"تواصل لطيف وعمل جماعي وتجربة مريحة للزوار المحليين والدوليين."},location:{title:"موقع مركزي وسياحي",copy:"في قلب سيركجي وإمينونو، بالقرب من المعالم التاريخية والفنادق ووسائل النقل العام."}},
az:{kicker:"BİZİ KƏŞF EDİN",title:"Salon White hekayəsinə<br><em>yaxından baxın.</em>",link:"Haqqımızda",experience:{title:"Təcrübə və peşəkarlıq",copy:"15 illik təcrübə, diqqətli tətbiq və şəxsi üsluba yönəlmiş yanaşma."},team:{title:"Peşəkar və səmimi komanda",copy:"Gülərüz ünsiyyət, komanda işi və yerli-xarici qonaqlar üçün rahat təcrübə."},location:{title:"Mərkəzi və turistik məkan",copy:"SIRKECI & EMINÖNÜ və Eminönünün mərkəzində, tarixi məkanlara, otellərə və ictimai nəqliyyata yaxın."}}};
let last=null;function render(){const l=localStorage.getItem("salonWhiteLang")||"tr";if(l===last)return;last=l;const t=data[l]||data.en;document.querySelectorAll("[data-preview-i18n]").forEach(el=>{const key=el.dataset.previewI18n;const v=key.split(".").reduce((a,k)=>a&&a[k],t);if(v)el.innerHTML=v})}render();setInterval(render,700)})();