const translations={
tr:{nav:{services:"Hizmetler",salon:"Salon",about:"Hakkımızda",gallery:"Galeri",istanbul:"İstanbul",contact:"İletişim",whatsapp:"WhatsApp"},hero:{eyebrow:"HAIR & BEAUTY · EMİNÖNÜ–SİRKECİ / İSTANBUL",subtitle:"Kadınlar ve Erkekler için",copy:"İstanbul'un tarihi merkezinde saç ve bakım deneyimi.",book:"Randevu Al",call:"Salonu Ara",scroll:"KEŞFET"},intro:{title:"Eminönü–Sirkeci'nin kalbinde,<br><em>kişisel stiliniz.</em>",copy:"Salon White; kadın ve erkek saç hizmetlerini, modern salon konforunu ve İstanbul'un tarihi atmosferini tek bir deneyimde buluşturur.",link:"Bizi keşfet"},services:{kicker:"HİZMETLER",title:"Senin stilin.<br><em>Senin deneyimin.</em>"},feature:{title:"İçeri gir.<br><em>Atmosferi hisset.</em>",copy:"Sade, sıcak ve modern bir salon deneyimi; tarihi Eminönü–Sirkeci'nin tam merkezinde."},gallery:{kicker:"GALERİ",title:"Salon White'ı<br><em>yakından görün.</em>"},istanbul:{title:"Bir saç molası,<br><em>İstanbul'un kalbinde.</em>",copy:"Eminönü–Sirkeci; tarihi yarımadanın, alışverişin, otellerin ve İstanbul'un ikonik duraklarının kesiştiği noktada.",map:"Yol Tarifi Al"},contact:{kicker:"İLETİŞİM",title:"Randevunuz<br><em>hazır.</em>",salon:"Salon",support:"7/24 WhatsApp & Destek",address:"Adres",whatsapp:"WhatsApp'tan Randevu",call:"Bizi Arayın"},quick:{whatsapp:"WhatsApp",call:"Ara",map:"Harita"},footer:{right:"Man & Woman Coiffeur · Eminönü–Sirkeci · Istanbul"}},
en:{nav:{services:"Services",salon:"Salon",about:"About Us",gallery:"Gallery",istanbul:"Istanbul",contact:"Contact",whatsapp:"WhatsApp"},hero:{eyebrow:"HAIR & BEAUTY · Eminonu–Sirkeci / ISTANBUL",subtitle:"For Women & Men",copy:"A hair & beauty experience in the historic heart of Istanbul.",book:"Book Appointment",call:"Call Salon",scroll:"EXPLORE"},intro:{title:"In the heart of Eminonu–Sirkeci,<br><em>your personal style.</em>",copy:"Salon White brings women's and men's hair services together with modern comfort and the atmosphere of historic Istanbul.",link:"Discover us"},services:{kicker:"SERVICES",title:"Your style.<br><em>Your experience.</em>"},feature:{title:"Step inside.<br><em>Feel the atmosphere.</em>",copy:"A warm, modern salon experience in the heart of historic Eminonu–Sirkeci."},gallery:{kicker:"GALLERY",title:"See Salon White<br><em>up close.</em>"},istanbul:{title:"A beauty break,<br><em>in the heart of Istanbul.</em>",copy:"Eminonu–Sirkeci sits at the crossroads of Istanbul's historic peninsula, hotels, shopping and iconic landmarks.",map:"Get Directions"},contact:{kicker:"CONTACT",title:"Your appointment<br><em>starts here.</em>",salon:"Salon",support:"24/7 WhatsApp & Support",address:"Address",whatsapp:"Book via WhatsApp",call:"Call Us"},quick:{whatsapp:"WhatsApp",call:"Call",map:"Map"},footer:{right:"Man & Woman Coiffeur · Eminonu–Sirkeci · Istanbul"}},
de:{nav:{services:"Leistungen",salon:"Salon",about:"Über uns",gallery:"Galerie",istanbul:"Istanbul",contact:"Kontakt",whatsapp:"WhatsApp"},hero:{eyebrow:"HAIR & BEAUTY · Eminonu–Sirkeci / ISTANBUL",subtitle:"Für Frauen & Männer",copy:"Hair & Beauty im historischen Herzen Istanbuls.",book:"Termin buchen",call:"Salon anrufen",scroll:"ENTDECKEN"},intro:{title:"Im Herzen von Eminonu–Sirkeci,<br><em>Ihr persönlicher Stil.</em>",copy:"Salon White verbindet Damen- und Herrenservices mit modernem Komfort und der Atmosphäre des historischen Istanbul.",link:"Entdecken"},services:{kicker:"LEISTUNGEN",title:"Ihr Stil.<br><em>Ihr Erlebnis.</em>"},feature:{title:"Hereinkommen.<br><em>Atmosphäre spüren.</em>",copy:"Ein warmes, modernes Salonerlebnis im Herzen des historischen Eminonu–Sirkeci."},gallery:{kicker:"GALERIE",title:"Salon White<br><em>hautnah erleben.</em>"},istanbul:{title:"Eine Beauty-Pause,<br><em>im Herzen Istanbuls.</em>",copy:"Eminonu–Sirkeci liegt am Schnittpunkt der historischen Halbinsel, der Hotels, Einkaufsmöglichkeiten und Wahrzeichen Istanbuls.",map:"Route anzeigen",nearby:["Hagia Sophia","Großer Basar","Topkapı-Palast","Gewürzbasar"]},contact:{kicker:"KONTAKT",title:"Ihr Termin<br><em>beginnt hier.</em>",salon:"Salon",support:"24/7 WhatsApp & Support",address:"Adresse",whatsapp:"Termin per WhatsApp",call:"Uns anrufen"},quick:{whatsapp:"WhatsApp",call:"Anrufen",map:"Karte"},footer:{right:"Man & Woman Coiffeur · Eminonu–Sirkeci · Istanbul"}},
fr:{nav:{services:"Services",salon:"Salon",about:"À propos",gallery:"Galerie",istanbul:"Istanbul",contact:"Contact",whatsapp:"WhatsApp"},hero:{eyebrow:"HAIR & BEAUTY · Eminonu–Sirkeci / ISTANBUL",subtitle:"Pour femmes et hommes",copy:"Une expérience coiffure & beauté au cœur historique d'Istanbul.",book:"Prendre rendez-vous",call:"Appeler le salon",scroll:"DÉCOUVRIR"},intro:{title:"Au cœur de Eminonu–Sirkeci,<br><em>votre style personnel.</em>",copy:"Salon White réunit les services pour femmes et hommes dans un cadre moderne au cœur de l'Istanbul historique.",link:"Découvrir"},services:{kicker:"SERVICES",title:"Votre style.<br><em>Votre expérience.</em>"},feature:{title:"Entrez.<br><em>Ressentez l'atmosphère.</em>",copy:"Une expérience salon chaleureuse et moderne au cœur de Eminonu–Sirkeci."},gallery:{kicker:"GALERIE",title:"Découvrez Salon White<br><em>de près.</em>"},istanbul:{title:"Une pause beauté,<br><em>au cœur d'Istanbul.</em>",copy:"Eminonu–Sirkeci se trouve au cœur de la péninsule historique d'Istanbul.",map:"Itinéraire"},contact:{kicker:"CONTACT",title:"Votre rendez-vous<br><em>commence ici.</em>",salon:"Salon",support:"WhatsApp & Assistance 24/7",address:"Adresse",whatsapp:"Réserver via WhatsApp",call:"Appelez-nous"},quick:{whatsapp:"WhatsApp",call:"Appeler",map:"Carte"},footer:{right:"Man & Woman Coiffeur · Eminonu–Sirkeci · Istanbul"}},
es:{nav:{services:"Servicios",salon:"Salón",about:"Sobre nosotros",gallery:"Galería",istanbul:"Estambul",contact:"Contacto",whatsapp:"WhatsApp"},hero:{eyebrow:"HAIR & BEAUTY · Eminonu–Sirkeci / ESTAMBUL",subtitle:"Para mujeres y hombres",copy:"Una experiencia de cabello y belleza en el corazón histórico de Estambul.",book:"Reservar cita",call:"Llamar al salón",scroll:"DESCUBRIR"},intro:{title:"En el corazón de Eminonu–Sirkeci,<br><em>tu estilo personal.</em>",copy:"Salon White reúne servicios para mujeres y hombres con el confort moderno de un salón en el corazón del Estambul histórico.",link:"Descubrir"},services:{kicker:"SERVICIOS",title:"Tu estilo.<br><em>Tu experiencia.</em>"},feature:{title:"Entra.<br><em>Siente el ambiente.</em>",copy:"Una experiencia de salón cálida y moderna en el corazón de Eminonu–Sirkeci."},gallery:{kicker:"GALERÍA",title:"Conoce Salon White<br><em>de cerca.</em>"},istanbul:{title:"Una pausa de belleza,<br><em>en el corazón de Estambul.</em>",copy:"Eminonu–Sirkeci se encuentra en el corazón de la península histórica de Estambul.",map:"Cómo llegar"},contact:{kicker:"CONTACTO",title:"Tu cita<br><em>empieza aquí.</em>",salon:"Salón",support:"WhatsApp y soporte 24/7",address:"Dirección",whatsapp:"Reservar por WhatsApp",call:"Llámanos"},quick:{whatsapp:"WhatsApp",call:"Llamar",map:"Mapa"},footer:{right:"Man & Woman Coiffeur · Sirkeci · Eminonu · Estambul"}},
ru:{nav:{services:"Услуги",salon:"Салон",about:"О нас",gallery:"Галерея",istanbul:"Стамбул",contact:"Контакты",whatsapp:"WhatsApp"},hero:{eyebrow:"HAIR & BEAUTY · Eminonu–Sirkeci / ISTANBUL",subtitle:"Для женщин и мужчин",copy:"Салон красоты в самом сердце исторического Стамбула.",book:"Записаться",call:"Позвонить нам",scroll:"ОТКРЫТЬ"},intro:{title:"В самом сердце Eminonu–Sirkeci,<br><em>ваш индивидуальный стиль.</em>",copy:"Salon White объединяет услуги для женщин и мужчин с современным комфортом и атмосферой исторического Стамбула.",link:"Узнать больше"},services:{kicker:"УСЛУГИ",title:"Ваш стиль.<br><em>Ваш опыт.</em>"},feature:{title:"Войдите.<br><em>Почувствуйте атмосферу.</em>",copy:"Тёплая и современная атмосфера в самом сердце Eminonu–Sirkeci."},gallery:{kicker:"ГАЛЕРЕЯ",title:"Salon White<br><em>крупным планом.</em>"},istanbul:{title:"Бьюти-пауза,<br><em>в сердце Стамбула.</em>",copy:"Eminonu–Sirkeci находится в центре исторического полуострова Стамбула.",map:"Маршрут"},contact:{kicker:"КОНТАКТЫ",title:"Ваша запись<br><em>начинается здесь.</em>",salon:"Салон",support:"WhatsApp и поддержка 24/7",address:"Адрес",whatsapp:"Записаться через WhatsApp",call:"Позвонить"},quick:{whatsapp:"WhatsApp",call:"Позвонить",map:"Карта"},footer:{right:"Man & Woman Coiffeur · Eminonu–Sirkeci · Istanbul"}},
ar:{nav:{services:"الخدمات",salon:"الصالون",about:"من نحن",gallery:"المعرض",istanbul:"إسطنبول",contact:"اتصل بنا",whatsapp:"واتساب"},hero:{eyebrow:"HAIR & BEAUTY · Eminonu–Sirkeci / ISTANBUL",subtitle:"للنساء والرجال",copy:"تجربة شعر وجمال في قلب إسطنبول التاريخي.",book:"احجز موعداً",call:"اتصل بالصالون",scroll:"اكتشف"},intro:{title:"في قلب Eminonu–Sirkeci،<br><em>أسلوبك الخاص.</em>",copy:"يجمع Salon White خدمات الشعر للنساء والرجال مع الراحة العصرية وأجواء إسطنبول التاريخية.",link:"اكتشفنا"},services:{kicker:"الخدمات",title:"أسلوبك.<br><em>تجربتك.</em>"},feature:{title:"ادخل.<br><em>اشعر بالأجواء.</em>",copy:"تجربة صالون دافئة وعصرية في قلب Eminonu–Sirkeci التاريخي."},gallery:{kicker:"المعرض",title:"شاهد Salon White<br><em>عن قرب.</em>"},istanbul:{title:"استراحة جمال،<br><em>في قلب إسطنبول.</em>",copy:"يقع Eminonu–Sirkeci في قلب شبه الجزيرة التاريخية في إسطنبول.",map:"الاتجاهات"},contact:{kicker:"اتصل بنا",title:"موعدك<br><em>يبدأ من هنا.</em>",salon:"الصالون",support:"واتساب ودعم 24/7",address:"العنوان",whatsapp:"الحجز عبر واتساب",call:"اتصل بنا"},quick:{whatsapp:"واتساب",call:"اتصل",map:"الخريطة"},footer:{right:"Man & Woman Coiffeur · Eminonu–Sirkeci · Istanbul"}}
,az:{nav:{services:"Xidmətlər",salon:"Salon",about:"Haqqımızda",gallery:"Qalereya",istanbul:"Istanbul",contact:"Əlaqə",whatsapp:"WhatsApp"},hero:{eyebrow:"HAIR & BEAUTY · Eminonu–Sirkeci / ISTANBUL",subtitle:"Qadınlar və Kişilər üçün",copy:"Istanbulun tarixi mərkəzində saç və gözəllik təcrübəsi.",book:"Görüş təyin et",call:"Salona zəng et",scroll:"KƏŞF ET"},intro:{title:"Eminonu–Sirkeci-nin qəlbində,<br><em>şəxsi üslubunuz.</em>",copy:"Salon White qadın və kişi saç xidmətlərini müasir rahatlıq və tarixi Istanbulun atmosferi ilə bir araya gətirir.",link:"Bizi kəşf edin"},services:{kicker:"XİDMƏTLƏR",title:"Sizin üslubunuz.<br><em>Sizin təcrübəniz.</em>"},feature:{title:"İçəri daxil olun.<br><em>Atmosferi hiss edin.</em>",copy:"Tarixi Eminonu–Sirkeci-nin mərkəzində isti və müasir salon təcrübəsi."},gallery:{kicker:"QALEREYA",title:"Salon White-a<br><em>yaxından baxın.</em>"},istanbul:{title:"Gözəllik fasiləsi,<br><em>Istanbulun qəlbində.</em>",copy:"Eminonu–Sirkeci Istanbulun tarixi yarımadasının, otellərin, alış-verişin və məşhur görməli yerlərin kəsişməsində yerləşir.",map:"İstiqamətləri al"},contact:{kicker:"ƏLAQƏ",title:"Görüşünüz<br><em>buradan başlayır.</em>",salon:"Salon",support:"24/7 WhatsApp və dəstək",address:"Ünvan",whatsapp:"WhatsApp ilə görüş təyin et",call:"Bizə zəng edin"},quick:{whatsapp:"WhatsApp",call:"Zəng et",map:"Xəritə"},footer:{right:"Man & Woman Coiffeur · Eminonu–Sirkeci · Istanbul"}}};
const serviceCatalog={
woman:[
  {key:"hair_style",image:"hizmet-01-kadin-sac-kesimi.jpg",items:["haircut","blow_dry","wavy_blow_dry","curling","braids"]},
  {key:"colour",image:"hizmet-02-kadin-balayage.jpg",items:["root_colour","complete_colour","ombre_balayage","lighten_dye"]},
  {key:"extensions",image:"hizmet-04-kadin-extensions.jpg",items:["micro_extensions","bead_extensions","tape_extensions","weft_extensions"]},
  {key:"hair_care",image:"hizmet-05-kadin-keratin.jpg",items:["keratin_care","botox_care","hair_treatment","restorative_mask","perm"]},
  {key:"beauty_care",image:"hizmet-06-kadin-treatment.jpg",items:["manicure","pedicure","makeup","eyebrow_moustache","face_brow_wax","full_skin_care"]}
],
man:[
  {key:"hair_beard",image:"hizmet-07-erkek-sac-kesimi.jpg",items:["mens_haircut","shave","beard_styling","wash_blow_dry","hair_beard_wash","hair_colour","keratin"]},
  {key:"grooming",image:"hizmet-12-erkek-grooming.jpg",items:["waxing_brow","brow_pluck","manicure","pedicure","skin_cleansing","full_skin_care"]}
]};
const serviceText={
tr:{
  hair_style:"Saç Kesimi & Şekillendirme",colour:"Saç Boyama & Renk",extensions:"Saç Kaynak",hair_care:"Saç Bakımı",beauty_care:"Güzellik & Bakım",hair_beard:"Saç & Sakal",grooming:"Erkek Bakım",
  haircut:"Saç Kesimi",blow_dry:"Düz Fön",wavy_blow_dry:"Dalgalı Fön",curling:"Maşa",braids:"Örgü",root_colour:"Dip Boya",complete_colour:"Komple Boya",ombre_balayage:"Ombre & Balayage",lighten_dye:"Renk Açma & Boyama",
  micro_extensions:"Mikro Kaynak",bead_extensions:"Boncuk Kaynak",tape_extensions:"Bant Kaynak",weft_extensions:"Tres Kaynak",
  keratin_care:"Keratin Bakımı",botox_care:"Botox Bakımı",hair_treatment:"Saç Tedavisi",restorative_mask:"Saç Maskesi",perm:"Perma",
  manicure:"Manikür",pedicure:"Pedikür",makeup:"Makyaj",eyebrow_moustache:"Kaş Tasarımı & Bıyık",face_brow_wax:"Yüz & Kaş Ağda",full_skin_care:"Full Cilt Bakımı",
  mens_haircut:"Erkek Saç Kesimi",shave:"Sakal Tıraşı",beard_styling:"Model Sakal & Şekillendirme",wash_blow_dry:"Yıkama & Fön",hair_beard_wash:"Saç & Sakal Yıkama",hair_colour:"Saç Boyama",keratin:"Keratin",
  waxing_brow:"Ağda & Kaş",brow_pluck:"Kaş Alma",skin_cleansing:"Cilt Temizleme"
},
en:{
  hair_style:"Haircut & Styling",colour:"Hair Colour",extensions:"Hair Extensions",hair_care:"Hair Care",beauty_care:"Beauty & Care",hair_beard:"Hair & Beard",grooming:"Men's Grooming",
  haircut:"Haircut",blow_dry:"Blow Dry",wavy_blow_dry:"Wavy Blow Dry",curling:"Curling Tongs",braids:"Braids",root_colour:"Root Colour",complete_colour:"Complete Hair Colour",ombre_balayage:"Ombre & Balayage",lighten_dye:"Colour Lightening & Dyeing",
  micro_extensions:"Micro Hair Extensions",bead_extensions:"Beaded Hair Extensions",tape_extensions:"Tape Hair Extensions",weft_extensions:"Weft / Tres Hair Extensions",
  keratin_care:"Keratin Care",botox_care:"Hair Botox Care",hair_treatment:"Hair Treatment",restorative_mask:"Restorative Hair Mask",perm:"Permanent Wave",
  manicure:"Manicure",pedicure:"Pedicure",makeup:"Make-up",eyebrow_moustache:"Eyebrow Design & Moustache",face_brow_wax:"Face & Eyebrow Wax",full_skin_care:"Full Skin Care",
  mens_haircut:"Men's Haircut",shave:"Shave",beard_styling:"Beard Styling",wash_blow_dry:"Wash + Blow Dry",hair_beard_wash:"Hair & Beard Wash",hair_colour:"Hair Colour",keratin:"Keratin",
  waxing_brow:"Waxing & Eyebrow",brow_pluck:"Eyebrow Plucking",skin_cleansing:"Skin Cleansing"
},
de:{
  hair_style:"Haarschnitt & Styling",colour:"Haarfarbe",extensions:"Haarverlängerung",hair_care:"Haarpflege",beauty_care:"Beauty & Pflege",hair_beard:"Haare & Bart",grooming:"Herrenpflege",
  haircut:"Haarschnitt",blow_dry:"Föhnen",wavy_blow_dry:"Wellen-Föhnen",curling:"Lockenstab",braids:"Flechten",root_colour:"Ansatzfärbung",complete_colour:"Komplettfärbung",ombre_balayage:"Ombré & Balayage",lighten_dye:"Aufhellen & Färben",
  micro_extensions:"Mikro-Haarverlängerung",bead_extensions:"Bonding mit Perlen",tape_extensions:"Tape-Extensions",weft_extensions:"Weft / Tres Extensions",
  keratin_care:"Keratinpflege",botox_care:"Haar-Botox-Pflege",hair_treatment:"Haarbehandlung",restorative_mask:"Aufbauende Haarmaske",perm:"Dauerwelle",
  manicure:"Maniküre",pedicure:"Pediküre",makeup:"Make-up",eyebrow_moustache:"Augenbrauen-Design & Damenbart",face_brow_wax:"Gesichts- & Augenbrauenwachs",full_skin_care:"Ganzheitliche Gesichtspflege",
  mens_haircut:"Herrenhaarschnitt",shave:"Rasur",beard_styling:"Bartstyling",wash_blow_dry:"Waschen & Föhnen",hair_beard_wash:"Haar- & Bartwäsche",hair_colour:"Haarfarbe",keratin:"Keratin",
  waxing_brow:"Waxing & Augenbrauen",brow_pluck:"Augenbrauen zupfen",skin_cleansing:"Hautreinigung"
},
fr:{
  hair_style:"Coupe & Coiffage",colour:"Couleur des Cheveux",extensions:"Extensions de Cheveux",hair_care:"Soins des Cheveux",beauty_care:"Beauté & Soins",hair_beard:"Cheveux & Barbe",grooming:"Soins Homme",
  haircut:"Coupe de Cheveux",blow_dry:"Brushing",wavy_blow_dry:"Brushing Ondulé",curling:"Boucles au Fer",braids:"Tresses",root_colour:"Coloration des Racines",complete_colour:"Coloration Complète",ombre_balayage:"Ombré & Balayage",lighten_dye:"Éclaircissement & Coloration",
  micro_extensions:"Extensions Micro",bead_extensions:"Extensions à Anneaux",tape_extensions:"Extensions Adhésives",weft_extensions:"Extensions Weft / Tres",
  keratin_care:"Soin à la Kératine",botox_care:"Soin Botox Capillaire",hair_treatment:"Traitement Capillaire",restorative_mask:"Masque Réparateur",perm:"Permanente",
  manicure:"Manucure",pedicure:"Pédicure",makeup:"Maquillage",eyebrow_moustache:"Design des Sourcils & Lèvre Supérieure",face_brow_wax:"Épilation Visage & Sourcils",full_skin_care:"Soin Complet de la Peau",
  mens_haircut:"Coupe Homme",shave:"Rasage",beard_styling:"Taille & Styling de Barbe",wash_blow_dry:"Shampoing & Brushing",hair_beard_wash:"Lavage Cheveux & Barbe",hair_colour:"Couleur Homme",keratin:"Kératine",
  waxing_brow:"Épilation & Sourcils",brow_pluck:"Épilation des Sourcils",skin_cleansing:"Nettoyage de la Peau"
},
es:{
  hair_style:"Corte & Peinado",colour:"Coloración",extensions:"Extensiones de Cabello",hair_care:"Cuidado Capilar",beauty_care:"Belleza & Cuidado",hair_beard:"Cabello & Barba",grooming:"Cuidado Masculino",
  haircut:"Corte de Pelo",blow_dry:"Secado con Cepillo",wavy_blow_dry:"Brushing Ondulado",curling:"Ondulado con Tenacilla",braids:"Trenzas",root_colour:"Coloración de Raíces",complete_colour:"Coloración Completa",ombre_balayage:"Ombré & Balayage",lighten_dye:"Decoloración & Coloración",
  micro_extensions:"Extensiones Micro",bead_extensions:"Extensiones con Microperlas",tape_extensions:"Extensiones de Cinta",weft_extensions:"Extensiones Weft / Tres",
  keratin_care:"Tratamiento de Queratina",botox_care:"Botox Capilar",hair_treatment:"Tratamiento Capilar",restorative_mask:"Mascarilla Reparadora",perm:"Permanente",
  manicure:"Manicura",pedicure:"Pedicura",makeup:"Maquillaje",eyebrow_moustache:"Diseño de Cejas & Labio Superior",face_brow_wax:"Depilación de Rostro & Cejas",full_skin_care:"Cuidado Facial Completo",
  mens_haircut:"Corte de Hombre",shave:"Afeitado",beard_styling:"Diseño y Styling de Barba",wash_blow_dry:"Lavado & Secado",hair_beard_wash:"Lavado de Cabello & Barba",hair_colour:"Coloración Masculina",keratin:"Queratina",
  waxing_brow:"Depilación & Cejas",brow_pluck:"Perfilado de Cejas",skin_cleansing:"Limpieza Facial"
},
ru:{
  hair_style:"Стрижка и укладка",colour:"Окрашивание",extensions:"Наращивание волос",hair_care:"Уход за волосами",beauty_care:"Красота и уход",hair_beard:"Волосы и борода",grooming:"Мужской уход",
  haircut:"Стрижка",blow_dry:"Укладка феном",wavy_blow_dry:"Волнистая укладка",curling:"Укладка плойкой",braids:"Косы",root_colour:"Окрашивание корней",complete_colour:"Полное окрашивание",ombre_balayage:"Омбре и балаяж",lighten_dye:"Осветление и окрашивание",
  micro_extensions:"Микро-наращивание",bead_extensions:"Наращивание на микрокольца",tape_extensions:"Ленточное наращивание",weft_extensions:"Тресс / Weft-наращивание",
  keratin_care:"Кератиновый уход",botox_care:"Ботокс-уход для волос",hair_treatment:"Лечение волос",restorative_mask:"Восстанавливающая маска",perm:"Химическая завивка",
  manicure:"Маникюр",pedicure:"Педикюр",makeup:"Макияж",eyebrow_moustache:"Оформление бровей и верхней губы",face_brow_wax:"Воск для лица и бровей",full_skin_care:"Комплексный уход за кожей",
  mens_haircut:"Мужская стрижка",shave:"Бритьё",beard_styling:"Моделирование бороды",wash_blow_dry:"Мытьё и укладка",hair_beard_wash:"Мытьё волос и бороды",hair_colour:"Мужское окрашивание",keratin:"Кератин",
  waxing_brow:"Воск и брови",brow_pluck:"Коррекция бровей",skin_cleansing:"Очищение кожи"
},
ar:{
  hair_style:"قص وتصفيف الشعر",colour:"صبغة ولون الشعر",extensions:"وصلات الشعر",hair_care:"العناية بالشعر",beauty_care:"الجمال والعناية",hair_beard:"الشعر واللحية",grooming:"العناية الرجالية",
  haircut:"قص الشعر",blow_dry:"تصفيف بالسشوار",wavy_blow_dry:"تصفيف مموج",curling:"تصفيف بالفير",braids:"ضفائر",root_colour:"صبغة الجذور",complete_colour:"صبغة كاملة",ombre_balayage:"أومبريه وبالياج",lighten_dye:"تفتيح وصبغ الشعر",
  micro_extensions:"وصلات ميكرو",bead_extensions:"وصلات بالخرز",tape_extensions:"وصلات شريطية",weft_extensions:"وصلات تريس / Weft",
  keratin_care:"عناية بالكيراتين",botox_care:"بوتوكس الشعر",hair_treatment:"علاج الشعر",restorative_mask:"ماسك ترميم الشعر",perm:"بيرم",
  manicure:"مانيكير",pedicure:"باديكير",makeup:"مكياج",eyebrow_moustache:"تصميم الحواجب ومنطقة الشارب",face_brow_wax:"واكس للوجه والحواجب",full_skin_care:"عناية كاملة بالبشرة",
  mens_haircut:"قص شعر للرجال",shave:"حلاقة",beard_styling:"تشكيل وتصفيف اللحية",wash_blow_dry:"غسيل وتصفيف",hair_beard_wash:"غسيل الشعر واللحية",hair_colour:"صبغة شعر للرجال",keratin:"كيراتين",
  waxing_brow:"واكس وحواجب",brow_pluck:"تنظيف الحواجب",skin_cleansing:"تنظيف البشرة"
},
az:{
  hair_style:"Saç kəsimi və düzüm",colour:"Saç rəngi",extensions:"Saç əlavələri",hair_care:"Saç baxımı",beauty_care:"Gözəllik və baxım",hair_beard:"Saç və saqqal",grooming:"Kişi baxımı",
  haircut:"Saç kəsimi",blow_dry:"Düz fen",wavy_blow_dry:"Dalğalı fen",curling:"Maşa",braids:"Hörük",root_colour:"Dip boyası",complete_colour:"Tam saç boyası",ombre_balayage:"Ombre və Balayaj",lighten_dye:"Rəng açma və boyama",
  micro_extensions:"Mikro qaynaq",bead_extensions:"Muncuqlu qaynaq",tape_extensions:"Lent qaynaq",weft_extensions:"Tres / Weft qaynaq",
  keratin_care:"Keratin baxımı",botox_care:"Saç botoksu baxımı",hair_treatment:"Saç müalicəsi",restorative_mask:"Bərpaedici saç maskası",perm:"Permanent",
  manicure:"Manikür",pedicure:"Pedikür",makeup:"Makiyaj",eyebrow_moustache:"Qaş dizaynı və üst dodaq",face_brow_wax:"Üz və qaş ağdası",full_skin_care:"Tam dəri baxımı",
  mens_haircut:"Kişi saç kəsimi",shave:"Saqqal qırxımı",beard_styling:"Model saqqal və düzüm",wash_blow_dry:"Yuma və fen",hair_beard_wash:"Saç və saqqal yuma",hair_colour:"Saç boyası",keratin:"Keratin",
  waxing_brow:"Ağda və qaş",brow_pluck:"Qaş alma",skin_cleansing:"Dəri təmizlənməsi"
}};
const serviceTitles={tr:{woman:"Kadınlara Özel Hizmetlerimiz",man:"Erkeklere Özel Hizmetlerimiz"},en:{woman:"Our Services for Women",man:"Our Services for Men"},de:{woman:"Unsere Leistungen für Frauen",man:"Unsere Leistungen für Männer"},fr:{woman:"Nos services pour femmes",man:"Nos services pour hommes"},es:{woman:"Nuestros servicios para mujeres",man:"Nuestros servicios para hombres"},ru:{woman:"Наши услуги для женщин",man:"Наши услуги для мужчин"},ar:{woman:"خدماتنا للنساء",man:"خدماتنا للرجال"},az:{woman:"Qadın xidmətlərimiz",man:"Kişi xidmətlərimiz"}};
const serviceLeads={tr:"Fiyatlandırma göstermeden, kadın ve erkek hizmetlerimizi kategori bazında inceleyin.",en:"Explore our women's and men's services by category, without price listings.",de:"Entdecken Sie unsere Leistungen für Frauen und Männer übersichtlich nach Kategorien – ohne Preislisten.",fr:"Découvrez nos services pour femmes et hommes, classés par catégorie, sans afficher les prix.",es:"Descubre nuestros servicios para mujeres y hombres, organizados por categorías y sin mostrar precios.",ru:"Ознакомьтесь с услугами для женщин и мужчин по категориям — без отображения цен.",ar:"استعرضوا خدماتنا للنساء والرجال حسب الفئات، من دون عرض الأسعار.",az:"Qadın və kişi xidmətlərimizi qiymət göstərmədən kateqoriyalar üzrə kəşf edin."};
const modeWords={tr:{woman:"KADIN",man:"ERKEK"},en:{woman:"WOMAN",man:"MAN"},de:{woman:"FRAU",man:"MANN"},fr:{woman:"FEMME",man:"HOMME"},es:{woman:"MUJER",man:"HOMBRE"},ru:{woman:"ЖЕНЩИНА",man:"МУЖЧУЖИНА"},ar:{woman:"امرأة",man:"رجل"},az:{woman:"QADIN",man:"KİŞİ"}};
const nearbyTranslations={tr:["Ayasofya","Kapalıçarşı","Topkapı Sarayı","Mısır Çarşısı"],en:["Hagia Sophia","Grand Bazaar","Topkapı Palace","Spice Bazaar"],de:["Hagia Sophia","Großer Basar","Topkapı-Palast","Gewürzbasar"],fr:["Sainte-Sophie","Grand Bazar","Palais de Topkapı","Bazar aux épices"],es:["Santa Sofía","Gran Bazar","Palacio de Topkapı","Bazar de las Especias"],ru:["Собор Святой Софии","Гранд-базар","Дворец Топкапы","Египетский базар"],ar:["آيا صوفيا","البازار الكبير","قصر توبكابي","سوق التوابل"],az:["Ayasofya","Kapalıçarşı","Topkapı Sarayı","Misir Çarşısı"]};let mode=localStorage.getItem("salonWhiteMode")||"woman",lang=localStorage.getItem("salonWhiteLang")||"tr",slide=0,slideTimer=null,revealObserver=null;
const hoursTranslations={
tr:{kicker:"ÇALIŞMA SAATLERİ",title:"Çalışma Saatleri",note:"Her gün sizi ağırlamaktan mutluluk duyuyoruz.",days:{mon:"Pazartesi",tue:"Salı",wed:"Çarşamba",thu:"Perşembe",fri:"Cuma",sat:"Cumartesi",sun:"Pazar"}},
en:{kicker:"OPENING HOURS",title:"Opening Hours",note:"We are happy to welcome you every day.",days:{mon:"Monday",tue:"Tuesday",wed:"Wednesday",thu:"Thursday",fri:"Friday",sat:"Saturday",sun:"Sunday"}},
de:{kicker:"ÖFFNUNGSZEITEN",title:"Öffnungszeiten",note:"Wir freuen uns, Sie jeden Tag begrüßen zu dürfen.",days:{mon:"Montag",tue:"Dienstag",wed:"Mittwoch",thu:"Donnerstag",fri:"Freitag",sat:"Samstag",sun:"Sonntag"}},
fr:{kicker:"HORAIRES D’OUVERTURE",title:"Horaires d’ouverture",note:"Nous sommes heureux de vous accueillir chaque jour.",days:{mon:"Lundi",tue:"Mardi",wed:"Mercredi",thu:"Jeudi",fri:"Vendredi",sat:"Samedi",sun:"Dimanche"}},
es:{kicker:"HORARIO",title:"Horario de apertura",note:"Estaremos encantados de recibirte todos los días.",days:{mon:"Lunes",tue:"Martes",wed:"Miércoles",thu:"Jueves",fri:"Viernes",sat:"Sábado",sun:"Domingo"}},
ru:{kicker:"ЧАСЫ РАБОТЫ",title:"Часы работы",note:"Будем рады приветствовать вас каждый день.",days:{mon:"Понедельник",tue:"Вторник",wed:"Среда",thu:"Четверг",fri:"Пятница",sat:"Суббота",sun:"Воскресенье"}},
ar:{kicker:"ساعات العمل",title:"ساعات العمل",note:"يسعدنا استقبالكم كل يوم.",days:{mon:"الاثنين",tue:"الثلاثاء",wed:"الأربعاء",thu:"الخميس",fri:"الجمعة",sat:"السبت",sun:"الأحد"}},
az:{kicker:"İŞ SAATLARI",title:"İş Saatları",note:"Sizi hər gün qarşılamaqdan məmnun olarıq.",days:{mon:"Bazar ertəsi",tue:"Çərşənbə axşamı",wed:"Çərşənbə",thu:"Cümə axşamı",fri:"Cümə",sat:"Şənbə",sun:"Bazar"}}
};
const serviceTitles={tr:{woman:"Kadınlara Özel Hizmetlerimiz",man:"Erkeklere Özel Hizmetlerimiz"},en:{woman:"Our Services for Women",man:"Our Services for Men"},de:{woman:"Unsere Leistungen für Frauen",man:"Unsere Leistungen für Männer"},fr:{woman:"Nos services pour femmes",man:"Nos services pour hommes"},es:{woman:"Nuestros servicios para mujeres",man:"Nuestros servicios para hombres"},ru:{woman:"Наши услуги для женщин",man:"Наши услуги для мужчин"},ar:{woman:"خدماتنا الخاصة للنساء",man:"خدماتنا الخاصة للرجال"},az:{woman:"Qadınlar üçün xüsusi xidmətlərimiz",man:"Kişilər üçün xüsusi xidmətlərimiz"}};
const modeWords={tr:{woman:"KADIN",man:"ERKEK"},en:{woman:"WOMAN",man:"MAN"},de:{woman:"FRAU",man:"MANN"},fr:{woman:"FEMME",man:"HOMME"},es:{woman:"MUJER",man:"HOMBRE"},ru:{woman:"ЖЕНЩИНА",man:"МУЖЧИНА"},ar:{woman:"امرأة",man:"رجل"},az:{woman:"QADIN",man:"KİŞİ"}};const getPath=(o,k)=>k.split(".").reduce((v,x)=>v?.[x],o);
function renderServices(){const grid=document.getElementById("serviceGrid"),nav=document.getElementById("serviceCategoryNav");if(!grid)return;const items=serviceCatalog[mode]||serviceCatalog.woman,t=serviceText[lang]||serviceText.en;grid.innerHTML=items.map((cat,i)=>`<article class="service-card service-category-card reveal" id="service-category-${cat.key}"><div class="service-visual"><img src="assets/images/${cat.image}" loading="lazy" decoding="async" alt="${t[cat.key]||cat.key}" onerror="this.parentElement.classList.add('missing')"></div><div class="service-category-meta"><span class="service-index">0${i+1}</span><span class="service-category-label">${t[cat.key]||cat.key}</span></div><h3>${t[cat.key]||cat.key}</h3><ul class="service-category-list">${cat.items.map(key=>`<li>${t[key]||key}</li>`).join("")}</ul></article>`).join("");if(nav){nav.innerHTML=items.map(cat=>`<a href="#service-category-${cat.key}" class="service-category-link">${t[cat.key]||cat.key}</a>`).join("");}const label=document.getElementById("modeLabel");if(label)label.textContent=serviceTitles[lang]?.[mode]||serviceTitles.en[mode];observeReveals();}
function applyLanguage(){const t=translations[lang]||translations.en;const serviceTitle=document.querySelector("[data-i18n=\"services.title\"]");if(serviceTitle)serviceTitle.innerHTML=serviceTitles[lang]?.[mode]||serviceTitles.en[mode];const serviceLead=document.querySelector("[data-i18n=\"services.lead\"]");if(serviceLead)serviceLead.textContent=serviceLeads[lang]||serviceLeads.en;const modeTitle=document.querySelector("[data-i18n=\"services.modeTitle\"]");if(modeTitle)modeTitle.textContent=serviceTitles[lang]?.[mode]||serviceTitles.en[mode];const ht=hoursTranslations[lang]||hoursTranslations.en;document.querySelector("[data-hours-kicker]")&&(document.querySelector("[data-hours-kicker]").textContent=ht.kicker);document.querySelector("[data-hours-title]")&&(document.querySelector("[data-hours-title]").textContent=ht.title);document.querySelector("[data-hours-note]")&&(document.querySelector("[data-hours-note]").textContent=ht.note);document.querySelectorAll("[data-day]").forEach(el=>{el.textContent=ht.days[el.dataset.day]||el.textContent});document.documentElement.lang=lang;document.documentElement.dir=lang==="ar"?"rtl":"ltr";document.querySelectorAll("[data-i18n]").forEach(el=>{const v=getPath(t,el.dataset.i18n);if(v)el.innerHTML=v;});const lb=document.getElementById("langButton");if(lb)lb.textContent=lang.toUpperCase();localStorage.setItem("salonWhiteLang",lang);const subtitle=document.getElementById("heroSubtitle");if(subtitle)subtitle.textContent=t.hero.subtitle;const title=document.getElementById("heroTitle");if(title)title.innerHTML=lang==="tr"?'<span>Salon</span> White<br><em class="hero-location-main">EMİNÖNÜ–SİRKECİ</em>':'<span>Salon</span> White<br><em class="hero-location-main">EMINONU–SIRKECI</em>';document.querySelectorAll("[data-mode-switch]").forEach(btn=>{btn.textContent=modeWords[lang]?.[btn.dataset.modeSwitch]||btn.dataset.modeSwitch.toUpperCase();});const nearby=document.getElementById("nearbyList");if(nearby)nearby.innerHTML=(nearbyTranslations[lang]||nearbyTranslations.en).map(x=>`<span>${x}</span>`).join("");}
function setMode(next){if(!["woman","man"].includes(next))return;mode=next;document.body.dataset.mode=mode;document.querySelectorAll(".mode-option").forEach(b=>{const active=b.dataset.modeSwitch===mode;b.classList.toggle("active",active);b.setAttribute("aria-pressed",active?"true":"false");});localStorage.setItem("salonWhiteMode",mode);applyLanguage();renderServices();}
window.setMode=setMode;
function setupMobileMenu(){const button=document.getElementById("menuButton"),menu=document.getElementById("mobileMenu"),langMenu=document.getElementById("langMenu"),langButton=document.getElementById("langButton");if(!button||!menu)return;const close=()=>{menu.classList.remove("open");menu.hidden=true;button.setAttribute("aria-expanded","false");document.body.classList.remove("menu-open");};button.addEventListener("click",e=>{e.stopPropagation();if(langMenu){langMenu.classList.remove("open");}if(langButton){langButton.setAttribute("aria-expanded","false");}const open=!menu.classList.contains("open");if(open){menu.hidden=false;menu.classList.remove("open");requestAnimationFrame(()=>requestAnimationFrame(()=>menu.classList.add("open")));}else{menu.classList.remove("open");setTimeout(()=>{if(!menu.classList.contains("open"))menu.hidden=true},360);}button.setAttribute("aria-expanded",open?"true":"false");document.body.classList.toggle("menu-open",open);});menu.querySelectorAll("a").forEach(a=>a.addEventListener("click",close));document.addEventListener("click",e=>{if(!e.target.closest("#mobileMenu")&&!e.target.closest("#menuButton"))close();});document.addEventListener("keydown",e=>{if(e.key==="Escape")close();});}
function setupLanguage(){const b=document.getElementById("langButton"),m=document.getElementById("langMenu"),mobile=document.getElementById("mobileMenu"),mobileButton=document.getElementById("menuButton");if(!b||!m)return;b.addEventListener("click",e=>{e.stopPropagation();if(mobile){mobile.classList.remove("open");mobile.hidden=true;}if(mobileButton){mobileButton.setAttribute("aria-expanded","false");}const open=!m.classList.contains("open");m.classList.toggle("open",open);b.setAttribute("aria-expanded",open?"true":"false");});m.querySelectorAll("[data-lang]").forEach(x=>x.addEventListener("click",()=>{lang=x.dataset.lang;applyLanguage();renderServices();m.classList.remove("open");b.setAttribute("aria-expanded","false");}));document.addEventListener("click",e=>{if(!e.target.closest(".lang-wrap")){m.classList.remove("open");b.setAttribute("aria-expanded","false");}});}
function setupHeroActionBar(){const bar=document.getElementById("mobileActionBar");if(!bar)return;const sync=()=>{const scroller=document.scrollingElement||document.documentElement;const scrollTop=scroller.scrollTop||window.scrollY||0;const viewport=scroller.clientHeight||window.innerHeight;const total=scroller.scrollHeight;const atEnd=scrollTop+viewport>=total-80;document.body.classList.toggle("page-end",atEnd);};sync();addEventListener("scroll",sync,{passive:true});addEventListener("resize",sync,{passive:true});addEventListener("pageshow",sync,{passive:true});setTimeout(sync,120);}
function observeReveals(){if(!revealObserver)revealObserver=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");revealObserver.unobserve(e.target);}}),{threshold:.12});document.querySelectorAll(".reveal:not(.visible)").forEach(e=>revealObserver.observe(e));}
function updateSlide(n){const slides=[...document.querySelectorAll(".hero-slide")];if(!slides.length)return;slides[slide]?.classList.remove("active");slide=(n+slides.length)%slides.length;slides[slide].classList.add("active");const c=document.getElementById("slideCounter");if(c)c.textContent=`0${slide+1} — 03`;}
function stopSlider(){if(slideTimer){clearInterval(slideTimer);slideTimer=null;}}
function startSlider(){stopSlider();if(document.hidden)return;slideTimer=setInterval(()=>{if(!document.hidden)updateSlide(slide+1);},6500);}
document.addEventListener("visibilitychange",()=>{if(document.hidden)stopSlider();else startSlider();});
function forceTopOnEntry(){if(location.hash&&location.hash!=="#top")return;requestAnimationFrame(()=>scrollTo({top:0,left:0,behavior:"auto"}));setTimeout(()=>scrollTo({top:0,left:0,behavior:"auto"}),80);}
function init(){const y=document.getElementById("year");if(y)y.textContent=new Date().getFullYear();forceTopOnEntry();document.body.dataset.mode=mode;document.querySelectorAll(".mode-option").forEach(b=>{const active=b.dataset.modeSwitch===mode;b.classList.toggle("active",active);b.setAttribute("aria-pressed",active?"true":"false");});setupMobileMenu();setupLanguage();setupHeroActionBar();applyLanguage();renderServices();observeReveals();startSlider();}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();

window.addEventListener("pageshow",()=>{if(!location.hash||location.hash==="#top")scrollTo({top:0,left:0,behavior:"auto"});});
