const translations={
tr:{nav:{services:"Hizmetler",salon:"Salon",gallery:"Galeri",istanbul:"İstanbul",contact:"İletişim",whatsapp:"WhatsApp"},hero:{eyebrow:"HAIR & BEAUTY · SİRKECİ / İSTANBUL",subtitle:"Kadınlar ve Erkekler için",copy:"İstanbul'un tarihi merkezinde saç ve bakım deneyimi.",book:"Randevu Al",call:"Salonu Ara",scroll:"KEŞFET"},intro:{title:"Sirkeci'nin kalbinde,<br><em>kişisel stiliniz.</em>",copy:"Salon White; kadın ve erkek saç hizmetlerini, modern salon konforunu ve İstanbul'un tarihi atmosferini tek bir deneyimde buluşturur.",link:"Bizi keşfet"},services:{kicker:"HİZMETLER",title:"Senin stilin.<br><em>Senin deneyimin.</em>"},feature:{title:"İçeri gir.<br><em>Atmosferi hisset.</em>",copy:"Sade, sıcak ve modern bir salon deneyimi; tarihi Sirkeci'nin tam merkezinde."},gallery:{kicker:"GALERİ",title:"Salon White'ı<br><em>yakından görün.</em>"},istanbul:{title:"Bir saç molası,<br><em>İstanbul'un kalbinde.</em>",copy:"Sirkeci; tarihi yarımadanın, alışverişin, otellerin ve İstanbul'un ikonik duraklarının kesiştiği noktada.",map:"Yol Tarifi Al"},contact:{kicker:"İLETİŞİM",title:"Randevunuz<br><em>hazır.</em>",salon:"Salon",support:"7/24 WhatsApp & Destek",address:"Adres",whatsapp:"WhatsApp'tan Randevu",call:"Ara"},quick:{whatsapp:"WhatsApp",call:"Ara",map:"Harita"},footer:{right:"Man & Woman Coiffeur · Istanbul"}},
en:{nav:{services:"Services",salon:"Salon",gallery:"Gallery",istanbul:"Istanbul",contact:"Contact",whatsapp:"WhatsApp"},hero:{eyebrow:"HAIR & BEAUTY · SIRKECI / ISTANBUL",subtitle:"For Women & Men",copy:"A hair & beauty experience in the historic heart of Istanbul.",book:"Book Appointment",call:"Call Salon",scroll:"EXPLORE"},intro:{title:"In the heart of Sirkeci,<br><em>your personal style.</em>",copy:"Salon White brings women's and men's hair services together with modern comfort and the atmosphere of historic Istanbul.",link:"Discover us"},services:{kicker:"SERVICES",title:"Your style.<br><em>Your experience.</em>"},feature:{title:"Step inside.<br><em>Feel the atmosphere.</em>",copy:"A warm, modern salon experience in the heart of historic Sirkeci."},gallery:{kicker:"GALLERY",title:"See Salon White<br><em>up close.</em>"},istanbul:{title:"A beauty break,<br><em>in the heart of Istanbul.</em>",copy:"Sirkeci sits at the crossroads of Istanbul's historic peninsula, hotels, shopping and iconic landmarks.",map:"Get Directions"},contact:{kicker:"CONTACT",title:"Your appointment<br><em>starts here.</em>",salon:"Salon",support:"24/7 WhatsApp & Support",address:"Address",whatsapp:"Book via WhatsApp",call:"Call"},quick:{whatsapp:"WhatsApp",call:"Call",map:"Map"},footer:{right:"Man & Woman Coiffeur · Istanbul"}},
de:{nav:{services:"Leistungen",salon:"Salon",gallery:"Galerie",istanbul:"Istanbul",contact:"Kontakt",whatsapp:"WhatsApp"},hero:{eyebrow:"HAIR & BEAUTY · SIRKECI / ISTANBUL",subtitle:"Für Frauen & Männer",copy:"Hair & Beauty im historischen Herzen Istanbuls.",book:"Termin buchen",call:"Salon anrufen",scroll:"ENTDECKEN"},intro:{title:"Im Herzen von Sirkeci,<br><em>Ihr persönlicher Stil.</em>",copy:"Salon White verbindet Damen- und Herrenservices mit modernem Komfort und der Atmosphäre des historischen Istanbul.",link:"Entdecken"},services:{kicker:"LEISTUNGEN",title:"Ihr Stil.<br><em>Ihr Erlebnis.</em>"},feature:{title:"Hereinkommen.<br><em>Atmosphäre spüren.</em>",copy:"Ein warmes, modernes Salonerlebnis im Herzen des historischen Sirkeci."},gallery:{kicker:"GALERIE",title:"Salon White<br><em>hautnah erleben.</em>"},istanbul:{title:"Eine Beauty-Pause,<br><em>im Herzen Istanbuls.</em>",copy:"Sirkeci liegt am Schnittpunkt der historischen Halbinsel, der Hotels, Einkaufsmöglichkeiten und Wahrzeichen Istanbuls.",map:"Route anzeigen",nearby:["Hagia Sophia","Großer Basar","Topkapı-Palast","Gewürzbasar"]},contact:{kicker:"KONTAKT",title:"Ihr Termin<br><em>beginnt hier.</em>",salon:"Salon",support:"24/7 WhatsApp & Support",address:"Adresse",whatsapp:"Termin per WhatsApp",call:"Anrufen"},quick:{whatsapp:"WhatsApp",call:"Anrufen",map:"Karte"},footer:{right:"Man & Woman Coiffeur · Istanbul"}},
fr:{nav:{services:"Services",salon:"Salon",gallery:"Galerie",istanbul:"Istanbul",contact:"Contact",whatsapp:"WhatsApp"},hero:{eyebrow:"HAIR & BEAUTY · SIRKECI / ISTANBUL",subtitle:"Pour femmes et hommes",copy:"Une expérience coiffure & beauté au cœur historique d'Istanbul.",book:"Prendre rendez-vous",call:"Appeler le salon",scroll:"DÉCOUVRIR"},intro:{title:"Au cœur de Sirkeci,<br><em>votre style personnel.</em>",copy:"Salon White réunit les services pour femmes et hommes dans un cadre moderne au cœur de l'Istanbul historique.",link:"Découvrir"},services:{kicker:"SERVICES",title:"Votre style.<br><em>Votre expérience.</em>"},feature:{title:"Entrez.<br><em>Ressentez l'atmosphère.</em>",copy:"Une expérience salon chaleureuse et moderne au cœur de Sirkeci."},gallery:{kicker:"GALERIE",title:"Découvrez Salon White<br><em>de près.</em>"},istanbul:{title:"Une pause beauté,<br><em>au cœur d'Istanbul.</em>",copy:"Sirkeci se trouve au cœur de la péninsule historique d'Istanbul.",map:"Itinéraire"},contact:{kicker:"CONTACT",title:"Votre rendez-vous<br><em>commence ici.</em>",salon:"Salon",support:"WhatsApp & Assistance 24/7",address:"Adresse",whatsapp:"Réserver via WhatsApp",call:"Appeler"},quick:{whatsapp:"WhatsApp",call:"Appeler",map:"Carte"},footer:{right:"Man & Woman Coiffeur · Istanbul"}},
es:{nav:{services:"Servicios",salon:"Salón",gallery:"Galería",istanbul:"Estambul",contact:"Contacto",whatsapp:"WhatsApp"},hero:{eyebrow:"HAIR & BEAUTY · SIRKECI / ESTAMBUL",subtitle:"Para mujeres y hombres",copy:"Una experiencia de cabello y belleza en el corazón histórico de Estambul.",book:"Reservar cita",call:"Llamar al salón",scroll:"DESCUBRIR"},intro:{title:"En el corazón de Sirkeci,<br><em>tu estilo personal.</em>",copy:"Salon White reúne servicios para mujeres y hombres con el confort moderno de un salón en el corazón del Estambul histórico.",link:"Descubrir"},services:{kicker:"SERVICIOS",title:"Tu estilo.<br><em>Tu experiencia.</em>"},feature:{title:"Entra.<br><em>Siente el ambiente.</em>",copy:"Una experiencia de salón cálida y moderna en el corazón de Sirkeci."},gallery:{kicker:"GALERÍA",title:"Conoce Salon White<br><em>de cerca.</em>"},istanbul:{title:"Una pausa de belleza,<br><em>en el corazón de Estambul.</em>",copy:"Sirkeci se encuentra en el corazón de la península histórica de Estambul.",map:"Cómo llegar"},contact:{kicker:"CONTACTO",title:"Tu cita<br><em>empieza aquí.</em>",salon:"Salón",support:"WhatsApp y soporte 24/7",address:"Dirección",whatsapp:"Reservar por WhatsApp",call:"Llamar"},quick:{whatsapp:"WhatsApp",call:"Llamar",map:"Mapa"},footer:{right:"Man & Woman Coiffeur · Estambul"}},
ru:{nav:{services:"Услуги",salon:"Салон",gallery:"Галерея",istanbul:"Стамбул",contact:"Контакты",whatsapp:"WhatsApp"},hero:{eyebrow:"HAIR & BEAUTY · СИРКЕДЖИ / СТАМБУЛ",subtitle:"Для женщин и мужчин",copy:"Салон красоты в самом сердце исторического Стамбула.",book:"Записаться",call:"Позвонить",scroll:"ОТКРЫТЬ"},intro:{title:"В самом сердце Сиркеджи,<br><em>ваш индивидуальный стиль.</em>",copy:"Salon White объединяет услуги для женщин и мужчин с современным комфортом и атмосферой исторического Стамбула.",link:"Узнать больше"},services:{kicker:"УСЛУГИ",title:"Ваш стиль.<br><em>Ваш опыт.</em>"},feature:{title:"Войдите.<br><em>Почувствуйте атмосферу.</em>",copy:"Тёплая и современная атмосфера в самом сердце Сиркеджи."},gallery:{kicker:"ГАЛЕРЕЯ",title:"Salon White<br><em>крупным планом.</em>"},istanbul:{title:"Бьюти-пауза,<br><em>в сердце Стамбула.</em>",copy:"Сиркеджи находится в центре исторического полуострова Стамбула.",map:"Маршрут"},contact:{kicker:"КОНТАКТЫ",title:"Ваша запись<br><em>начинается здесь.</em>",salon:"Салон",support:"WhatsApp и поддержка 24/7",address:"Адрес",whatsapp:"Записаться через WhatsApp",call:"Позвонить"},quick:{whatsapp:"WhatsApp",call:"Позвонить",map:"Карта"},footer:{right:"Man & Woman Coiffeur · Стамбул"}},
ar:{nav:{services:"الخدمات",salon:"الصالون",gallery:"المعرض",istanbul:"إسطنبول",contact:"اتصل بنا",whatsapp:"واتساب"},hero:{eyebrow:"HAIR & BEAUTY · سيركجي / إسطنبول",subtitle:"للنساء والرجال",copy:"تجربة شعر وجمال في قلب إسطنبول التاريخي.",book:"احجز موعداً",call:"اتصل بالصالون",scroll:"اكتشف"},intro:{title:"في قلب سيركجي،<br><em>أسلوبك الخاص.</em>",copy:"يجمع Salon White خدمات الشعر للنساء والرجال مع الراحة العصرية وأجواء إسطنبول التاريخية.",link:"اكتشفنا"},services:{kicker:"الخدمات",title:"أسلوبك.<br><em>تجربتك.</em>"},feature:{title:"ادخل.<br><em>اشعر بالأجواء.</em>",copy:"تجربة صالون دافئة وعصرية في قلب سيركجي التاريخي."},gallery:{kicker:"المعرض",title:"شاهد Salon White<br><em>عن قرب.</em>"},istanbul:{title:"استراحة جمال،<br><em>في قلب إسطنبول.</em>",copy:"يقع سيركجي في قلب شبه الجزيرة التاريخية في إسطنبول.",map:"الاتجاهات"},contact:{kicker:"اتصل بنا",title:"موعدك<br><em>يبدأ من هنا.</em>",salon:"الصالون",support:"واتساب ودعم 24/7",address:"العنوان",whatsapp:"الحجز عبر واتساب",call:"اتصل"},quick:{whatsapp:"واتساب",call:"اتصل",map:"الخريطة"},footer:{right:"Man & Woman Coiffeur · إسطنبول"}}
,az:{nav:{services:"Xidmətlər",salon:"Salon",gallery:"Qalereya",istanbul:"İstanbul",contact:"Əlaqə",whatsapp:"WhatsApp"},hero:{eyebrow:"HAIR & BEAUTY · SİRKECİ / İSTANBUL",subtitle:"Qadınlar və Kişilər üçün",copy:"İstanbulun tarixi mərkəzində saç və gözəllik təcrübəsi.",book:"Görüş təyin et",call:"Salona zəng et",scroll:"KƏŞF ET"},intro:{title:"Sirkecinin qəlbində,<br><em>şəxsi üslubunuz.</em>",copy:"Salon White qadın və kişi saç xidmətlərini müasir rahatlıq və tarixi İstanbulun atmosferi ilə bir araya gətirir.",link:"Bizi kəşf edin"},services:{kicker:"XİDMƏTLƏR",title:"Sizin üslubunuz.<br><em>Sizin təcrübəniz.</em>"},feature:{title:"İçəri daxil olun.<br><em>Atmosferi hiss edin.</em>",copy:"Tarixi Sirkecinin mərkəzində isti və müasir salon təcrübəsi."},gallery:{kicker:"QALEREYA",title:"Salon White-a<br><em>yaxından baxın.</em>"},istanbul:{title:"Gözəllik fasiləsi,<br><em>İstanbulun qəlbində.</em>",copy:"Sirkeci İstanbulun tarixi yarımadasının, otellərin, alış-verişin və məşhur görməli yerlərin kəsişməsində yerləşir.",map:"İstiqamətləri al"},contact:{kicker:"ƏLAQƏ",title:"Görüşünüz<br><em>buradan başlayır.</em>",salon:"Salon",support:"24/7 WhatsApp və dəstək",address:"Ünvan",whatsapp:"WhatsApp ilə görüş təyin et",call:"Zəng et"},quick:{whatsapp:"WhatsApp",call:"Zəng et",map:"Xəritə"},footer:{right:"Man & Woman Coiffeur · İstanbul"}}};
const serviceCopy={
woman:{
tr:[["01","Saç Kesimi & Styling","Kesim, fön ve günlük saç şekillendirme."],["02","Balayage & Highlights","Işıltı ve doğal renk geçişleri."],["03","Ombre","Modern ve yumuşak renk geçişleri."],["04","Hair Extensions","Uzunluk ve hacim için saç uygulamaları."],["05","Keratin Hair","Pürüzsüzlük ve bakım odaklı uygulamalar."],["06","Hair Treatment","Saçın görünümünü ve bakımını destekleyen uygulamalar."]],
en:[["01","Cut & Styling","Cuts, blow-dry and everyday styling."],["02","Balayage & Highlights","Light-catching colour and natural transitions."],["03","Ombre","Soft, modern colour gradients."],["04","Hair Extensions","Length and volume enhancement."],["05","Keratin Hair","Smoothness and care-focused treatment."],["06","Hair Treatment","Professional care for healthier-looking hair."]],
de:[["01","Schnitt & Styling","Haarschnitt, Föhnen und Styling."],["02","Balayage & Highlights","Lichteffekte und natürliche Farbübergänge."],["03","Ombré","Weiche, moderne Farbübergänge."],["04","Hair Extensions","Mehr Länge und Volumen."],["05","Keratin Hair","Glätte und pflegende Anwendung."],["06","Hair Treatment","Pflege für ein gepflegtes Haarbild."]],
fr:[["01","Coupe & Styling","Coupe, brushing et coiffage."],["02","Balayage & Highlights","Lumière et transitions de couleur naturelles."],["03","Ombré","Dégradés modernes et doux."],["04","Extensions","Longueur et volume."],["05","Soin Kératine","Lissage et soin."],["06","Soin des Cheveux","Soin professionnel pour les cheveux."]],
es:[["01","Corte & Styling","Corte, brushing y peinado."],["02","Balayage & Highlights","Luz y transiciones de color naturales."],["03","Ombré","Degradados suaves y modernos."],["04","Extensiones","Más longitud y volumen."],["05","Tratamiento de Keratina","Suavidad y cuidado."],["06","Tratamiento Capilar","Cuidado profesional del cabello."]],
ru:[["01","Стрижка и укладка","Стрижка, укладка и ежедневный стиль."],["02","Balayage и Highlights","Естественные переходы и сияние."],["03","Омбре","Мягкие современные переходы цвета."],["04","Наращивание","Длина и объём волос."],["05","Кератиновый уход","Гладкость и уход."],["06","Уход за волосами","Профессиональный уход за волосами."]],
ar:[["01","قص وتصفيف الشعر","قص وتجفيف وتصفيف يومي."],["02","بالياج وهايلايت","إضاءة وانتقالات لونية طبيعية."],["03","أومبريه","تدرجات لونية عصرية وناعمة."],["04","وصلات الشعر","لزيادة الطول والكثافة."],["05","علاج الكيراتين","نعومة وعناية بالشعر."],["06","عناية بالشعر","عناية احترافية بمظهر الشعر."]],az:[["01","Saç kəsimi və saç düzümü","Kəsim, fen və gündəlik saç düzümü."],["02","Balayage və Highlights","Təbii rəng keçidləri və işıltı."],["03","Ombre","Müasir və yumşaq rəng keçidləri."],["04","Saç əlavələri","Uzunluq və həcm üçün saç tətbiqləri."],["05","Keratin baxımı","Hamarlıq və saç baxımına yönəlmiş tətbiq."],["06","Saç baxımı","Saçın görünüşünü dəstəkləyən peşəkar qulluq."]]
},
man:{
tr:[["01","Erkek Saç Kesimi","Modern ve klasik erkek saç kesimleri."],["02","Saç & Sakal","Saç ve sakal için birlikte bakım."],["03","Sakal Styling","Sakal şekillendirme ve detay bakımı."],["04","Erkek Styling","Günlük ve özel günler için şekillendirme."],["05","Hair Treatment","Saç bakımına yönelik profesyonel uygulamalar."],["06","Classic Grooming","Temiz ve düzenli kişisel bakım."]],
en:[["01","Men's Haircut","Modern and classic men's cuts."],["02","Hair & Beard","A complete hair and beard service."],["03","Beard Styling","Beard shaping and detail grooming."],["04","Men's Styling","Everyday and occasion styling."],["05","Hair Treatment","Professional hair care."],["06","Classic Grooming","Clean, refined personal grooming."]],
de:[["01","Herrenhaarschnitt","Moderne und klassische Haarschnitte."],["02","Haar & Bart","Haar- und Bartpflege kombiniert."],["03","Bartstyling","Bartform und Detailpflege."],["04","Herrenstyling","Styling für Alltag und Anlass."],["05","Haarpflege","Professionelle Haarpflege."],["06","Classic Grooming","Gepflegte persönliche Routine."]],
fr:[["01","Coupe Homme","Coupes modernes et classiques."],["02","Cheveux & Barbe","Soin complet cheveux et barbe."],["03","Barbe","Taille et mise en forme."],["04","Styling Homme","Coiffage quotidien ou événement."],["05","Soin des Cheveux","Soin professionnel."],["06","Grooming Classique","Une routine de soin soignée."]],
es:[["01","Corte Hombre","Cortes modernos y clásicos."],["02","Cabello & Barba","Servicio completo de cabello y barba."],["03","Styling de Barba","Perfilado y cuidado."],["04","Styling Hombre","Peinado diario y para ocasiones."],["05","Tratamiento Capilar","Cuidado profesional."],["06","Grooming Clásico","Cuidado personal limpio y cuidado."]],
ru:[["01","Мужская стрижка","Современные и классические стрижки."],["02","Волосы и борода","Комплексный уход за волосами и бородой."],["03","Укладка бороды","Форма и детальный уход."],["04","Мужская укладка","Для повседневного образа и события."],["05","Уход за волосами","Профессиональный уход."],["06","Классический уход","Аккуратный персональный уход."]],
ar:[["01","قص شعر رجالي","قصات عصرية وكلاسيكية."],["02","الشعر واللحية","عناية متكاملة بالشعر واللحية."],["03","تصفيف اللحية","تشكيل وعناية بالتفاصيل."],["04","تصفيف رجالي","تصفيف يومي وللمناسبات."],["05","عناية بالشعر","عناية احترافية بالشعر."],["06","العناية الكلاسيكية","روتين عناية شخصي أنيق."]],az:[["01","Kişi saç kəsimi","Müasir və klassik kişi saç kəsimləri."],["02","Saç və saqqal","Saç və saqqal üçün tam baxım."],["03","Saqqal düzümü","Saqqal forması və detallı baxım."],["04","Kişi saç düzümü","Gündəlik və xüsusi günlər üçün saç düzümü."],["05","Saç baxımı","Peşəkar saç baxımı."],["06","Klassik baxım","Səliqəli və zövqlü şəxsi baxım."]]
}};

const nearbyTranslations={tr:["Ayasofya","Kapalıçarşı","Topkapı Sarayı","Mısır Çarşısı"],en:["Hagia Sophia","Grand Bazaar","Topkapı Palace","Spice Bazaar"],de:["Hagia Sophia","Großer Basar","Topkapı-Palast","Gewürzbasar"],fr:["Sainte-Sophie","Grand Bazar","Palais de Topkapı","Bazar aux épices"],es:["Santa Sofía","Gran Bazar","Palacio de Topkapı","Bazar de las Especias"],ru:["Собор Святой Софии","Гранд-базар","Дворец Топкапы","Египетский базар"],ar:["آيا صوفيا","البازار الكبير","قصر توبكابي","سوق التوابل"],az:["Ayasofya","Kapalıçarşı","Topkapı Sarayı","Misir Çarşısı"]};let mode=localStorage.getItem("salonWhiteMode")||"woman",lang=localStorage.getItem("salonWhiteLang")||"tr",slide=0,slideTimer=null,revealObserver=null;
const modeWords={tr:{woman:"KADIN",man:"ERKEK"},en:{woman:"WOMAN",man:"MAN"},de:{woman:"FRAU",man:"MANN"},fr:{woman:"FEMME",man:"HOMME"},es:{woman:"MUJER",man:"HOMBRE"},ru:{woman:"ЖЕНЩИНА",man:"МУЖЧИНА"},ar:{woman:"امرأة",man:"رجل"},az:{woman:"QADIN",man:"KİŞİ"}};const getPath=(o,k)=>k.split(".").reduce((v,x)=>v?.[x],o);
function renderServices(){const grid=document.getElementById("serviceGrid");if(!grid)return;const items=serviceCopy[mode][lang]||serviceCopy[mode].en;const images=mode==="woman"?["hizmet-01-kadin-sac-kesimi.jpg","hizmet-02-kadin-balayage.jpg","hizmet-03-kadin-ombre.jpg","hizmet-04-kadin-extensions.jpg","hizmet-05-kadin-keratin.jpg","hizmet-06-kadin-treatment.jpg"]:["hizmet-07-erkek-sac-kesimi.jpg","hizmet-08-erkek-sac-sakal.jpg","hizmet-09-erkek-sakal.jpg","hizmet-10-erkek-styling.jpg","hizmet-11-erkek-treatment.jpg","hizmet-12-erkek-grooming.jpg"];grid.innerHTML=items.map((x,i)=>`<article class="service-card reveal"><div class="service-visual"><img src="assets/images/${images[i]}" loading="lazy" decoding="async" alt="${x[1]}" onerror="this.parentElement.classList.add('missing')"></div><span class="service-index">${x[0]}</span><div><h3>${x[1]}</h3><p>${x[2]}</p></div></article>`).join("");const label=document.getElementById("modeLabel");if(label)label.textContent=(modeWords[lang]?.[mode]||mode.toUpperCase())+(lang==="tr"?" DENEYİM":lang==="az"?" TƏCRÜBƏ":lang==="de"?" · ERLEBNIS":lang==="fr"?" · EXPÉRIENCE":lang==="es"?" · EXPERIENCIA":lang==="ru"?" · ОПЫТ":lang==="ar"?" · تجربة":" EXPERIENCE");observeReveals();}
function applyLanguage(){const t=translations[lang]||translations.en;document.documentElement.lang=lang;document.documentElement.dir=lang==="ar"?"rtl":"ltr";document.querySelectorAll("[data-i18n]").forEach(el=>{const v=getPath(t,el.dataset.i18n);if(v)el.innerHTML=v;});const lb=document.getElementById("langButton");if(lb)lb.textContent=lang.toUpperCase();localStorage.setItem("salonWhiteLang",lang);const subtitle=document.getElementById("heroSubtitle");if(subtitle)subtitle.textContent=t.hero.subtitle;const title=document.getElementById("heroTitle");if(title)title.innerHTML="<span>Salon</span> White<br><em>Sirkeci</em>";document.querySelectorAll("[data-mode-switch]").forEach(btn=>{btn.textContent=modeWords[lang]?.[btn.dataset.modeSwitch]||btn.dataset.modeSwitch.toUpperCase();});const nearby=document.getElementById("nearbyList");if(nearby)nearby.innerHTML=(nearbyTranslations[lang]||nearbyTranslations.en).map(x=>`<span>${x}</span>`).join("");}
function setMode(next){if(!["woman","man"].includes(next))return;mode=next;document.body.dataset.mode=mode;document.querySelectorAll(".mode-option").forEach(b=>{const active=b.dataset.modeSwitch===mode;b.classList.toggle("active",active);b.setAttribute("aria-pressed",active?"true":"false");});localStorage.setItem("salonWhiteMode",mode);applyLanguage();renderServices();}
window.setMode=setMode;
function setupMobileMenu(){const button=document.getElementById("menuButton"),menu=document.getElementById("mobileMenu"),langMenu=document.getElementById("langMenu"),langButton=document.getElementById("langButton");if(!button||!menu)return;const close=()=>{menu.classList.remove("open");menu.hidden=true;button.setAttribute("aria-expanded","false");document.body.classList.remove("menu-open");};button.addEventListener("click",e=>{e.stopPropagation();if(langMenu){langMenu.classList.remove("open");}if(langButton){langButton.setAttribute("aria-expanded","false");}const open=!menu.classList.contains("open");if(open){menu.hidden=false;menu.classList.remove("open");requestAnimationFrame(()=>requestAnimationFrame(()=>menu.classList.add("open")));}else{menu.classList.remove("open");setTimeout(()=>{if(!menu.classList.contains("open"))menu.hidden=true},360);}button.setAttribute("aria-expanded",open?"true":"false");document.body.classList.toggle("menu-open",open);});menu.querySelectorAll("a").forEach(a=>a.addEventListener("click",close));document.addEventListener("click",e=>{if(!e.target.closest("#mobileMenu")&&!e.target.closest("#menuButton"))close();});document.addEventListener("keydown",e=>{if(e.key==="Escape")close();});}
function setupLanguage(){const b=document.getElementById("langButton"),m=document.getElementById("langMenu"),mobile=document.getElementById("mobileMenu"),mobileButton=document.getElementById("menuButton");if(!b||!m)return;b.addEventListener("click",e=>{e.stopPropagation();if(mobile){mobile.classList.remove("open");mobile.hidden=true;}if(mobileButton){mobileButton.setAttribute("aria-expanded","false");}const open=!m.classList.contains("open");m.classList.toggle("open",open);b.setAttribute("aria-expanded",open?"true":"false");});m.querySelectorAll("[data-lang]").forEach(x=>x.addEventListener("click",()=>{lang=x.dataset.lang;applyLanguage();renderServices();m.classList.remove("open");b.setAttribute("aria-expanded","false");}));document.addEventListener("click",e=>{if(!e.target.closest(".lang-wrap")){m.classList.remove("open");b.setAttribute("aria-expanded","false");}});}
function setupHeroActionBar(){const bar=document.getElementById("mobileActionBar");if(!bar)return;const sync=()=>{const scroller=document.scrollingElement||document.documentElement;const scrollTop=scroller.scrollTop||window.scrollY||0;const viewport=scroller.clientHeight||window.innerHeight;const total=scroller.scrollHeight;const atEnd=scrollTop+viewport>=total-80;document.body.classList.toggle("page-end",atEnd);};sync();addEventListener("scroll",sync,{passive:true});addEventListener("resize",sync,{passive:true});addEventListener("pageshow",sync,{passive:true});setTimeout(sync,120);}
function observeReveals(){if(!revealObserver)revealObserver=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");revealObserver.unobserve(e.target);}}),{threshold:.12});document.querySelectorAll(".reveal:not(.visible)").forEach(e=>revealObserver.observe(e));}
function updateSlide(n){const slides=[...document.querySelectorAll(".hero-slide")];if(!slides.length)return;slides[slide]?.classList.remove("active");slide=(n+slides.length)%slides.length;slides[slide].classList.add("active");const c=document.getElementById("slideCounter");if(c)c.textContent=`0${slide+1} — 03`;}
function stopSlider(){if(slideTimer){clearInterval(slideTimer);slideTimer=null;}}
function startSlider(){stopSlider();if(document.hidden)return;slideTimer=setInterval(()=>{if(!document.hidden)updateSlide(slide+1);},6500);}
document.addEventListener("visibilitychange",()=>{if(document.hidden)stopSlider();else startSlider();});
function forceTopOnEntry(){if(location.hash&&location.hash!=="#top")return;requestAnimationFrame(()=>scrollTo({top:0,left:0,behavior:"auto"}));setTimeout(()=>scrollTo({top:0,left:0,behavior:"auto"}),80);}
function init(){const y=document.getElementById("year");if(y)y.textContent=new Date().getFullYear();forceTopOnEntry();document.body.dataset.mode=mode;document.querySelectorAll(".mode-option").forEach(b=>{const active=b.dataset.modeSwitch===mode;b.classList.toggle("active",active);b.setAttribute("aria-pressed",active?"true":"false");});setupMobileMenu();setupLanguage();setupHeroActionBar();applyLanguage();renderServices();observeReveals();startSlider();}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();

window.addEventListener("pageshow",()=>{if(!location.hash||location.hash==="#top")scrollTo({top:0,left:0,behavior:"auto"});});
